#!/usr/bin/env bash
# This bash script transfers a file from a client to a server using scp
# 
#The path to the file is to be transferred
#The IP of the server we want to transfer the file to
#The username scp connects with
#The path to the SSH private key that scp uses

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
