#!/usr/bin/env bash
# install nginx on my server ubuntu@100.26.214.164

sudo apt update
sudo apt upgrade -y

sudo apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
