#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely,
# with a sleep 2 in between each of the iteration.
# Displays "I am invincible!!!" in between each of the iteration.
while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible"' SIGTERM 
done
