#!/usr/bin/env bash
#fizzbuzz stuf

cont=1
while [ $cont -ne 101 ]
do
    if [ $((cont % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((cont % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((cont % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $cont
    fi
    ((cont++))
