#!/usr/bin/env bash
#fizzbuzz stuf

cnt=1
while [ $cnt -ne 101 ]
do
    if [ $((cnt % 15)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((cnt % 3)) -eq 0 ]
    then
	echo "Fizz"
    elif [ $((cnt % 5)) -eq 0 ]
    then
        echo "Buzz"
    else
	echo $cnt
    fi
    ((cnt++)
